CREATE TABLE PRODUTOS (
ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL, 
VALOR DOUBLE (9,2) NOT NULL,
DESCRICAO VARCHAR (70) NOT NULL,
QUANTIDADE INT NOT NULL,
FORNECEDORID INT UNSIGNED NOT NULL,
CATEGORIAID INT UNSIGNED NOT NULL,
IMAGEM VARCHAR (30) NOT NULL
)ENGINE = INNODB;

CREATE TABLE CATEGORIA (
ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
DESCRICAO VARCHAR(70) NOT NULL
) ENGINE = INNODB;

CREATE TABLE CLIENTES(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
TELEFONE CHAR(13) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
CEP CHAR(8) NOT NULL,
SEXO VARCHAR (20) NOT NULL,
EMAIL VARCHAR(70) NOT NULL,
SENHA VARCHAR (30) NOT NULL,
ENDERECO VARCHAR(70) NOT NULL
)ENGINE = INNODB;

CREATE TABLE FORNECEDOR(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
CNPJ CHAR(18) NOT NULL,
EMAIL VARCHAR(70) NOT NULL,
TELEFONE CHAR(13) NOT NULL,
NOME_REPRESENTANTE VARCHAR(40) NOT NULL,
TELEFONE_REPRESENTANTE CHAR(13) NOT NULL
)ENGINE = INNODB;
